### ISSUE TITLE
xs, sm, md, lg views inside the iframes

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-docs#101]
We need to discuss the layout and responsive aspect of the GUI elements. How we communicate and visualise them. I don't think it's working.

**Comment by justinspencer** [comment]
Moved to previous issue raised by Kate

**Comment by dominikwilkowski** [comment]
You can link an issue by stating the hash and the number together like so: #98
This helps us keep track on what is connected to what.
