### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-docs#104]
Need to get hold of the web licence's for all brand web fonts that are used in the GUI and add them to the downloads.
BOM = Stag
STG = Dragon Bold
BT = Helvetica Neue (Not yet implemented)
Westpac = Chronicle (Not yet implemented)
BSA = Aller (Not yet implemented)

**Comment by dominikwilkowski** [comment]
moved to WestpacCXTeam/GUI-source#231
