### ISSUE TITLE
iOS - hamburger

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-docs#45]
Fixed position not working

**Comment by dominikwilkowski** [comment]
lies!

screenshot please as it works nicely on mine :)

**Comment by justinspencer** [comment]
![image](https://cloud.githubusercontent.com/assets/936597/9409483/5a3f533a-485e-11e5-9ccf-08c98205854e.jpg)
![image](https://cloud.githubusercontent.com/assets/936597/9409484/5a94e6ba-485e-11e5-817b-0c3ae8195549.jpg)
