### ISSUE TITLE
duplicate copy

### ISSUE THREAD

**Issue by PeteClancy** [WestpacCXTeam/GUI-docs#63]
please remove the duplicate copy on http://gel.westpacgroup.com.au/GUI/WBC/forms/
radios > whats new. 

![image](https://cloud.githubusercontent.com/assets/10430317/9725087/36c21108-5624-11e5-97e6-31014ecc7052.png)

**Comment by dominikwilkowski** [comment]
fixed via cb6966df917d4fa3215f7738a4abb19126c85b62
