### ISSUE TITLE
input-addon-lg modifier class

### ISSUE THREAD

**Issue by astrotim** [WestpacCXTeam/GUI-docs#71]
`.input-addon-lg` exists but is not listed as a modifier class in docs.

**Comment by dominikwilkowski** [comment]
Should we include the sizing of the input field? We got four implemented.
- `sm`
- `md` which can be omitted as it's the default view
- `lg`
- `xl`

What do you think @justinspencer

**Comment by justinspencer** [comment]
Yep we should show all sizes in the the GUI Docs. To keep things simple would it be better to add a single sizing example and explain that this system applies to all the input components? Just a thought. I'm happy to go with whatever's most useful for developers.

**Comment by dominikwilkowski** [comment]
moved to WestpacCXTeam/GUI-source#223
