### ISSUE TITLE
Icon colour

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-docs#82]
All icons in the GUI docs should use the muted colour. Same as GUI 1.0. This is purely a visual enhancement for the GUI docs. It has nothing to do with the GUI source.

**Comment by dominikwilkowski** [comment]
So how would one find out what the default color is of all the icons? Would one be surprised to see that the icons after installing them be a different color than advertised in the docs? Would one then be frustrated about having to embed each and every single icon to make them look like the docs example?

Just talking hypothetical here sir... :)

**Comment by justinspencer** [comment]
One of the reasons for using svg's is so we can style them "easily". To achieve this the svg icon has to be embedded. I'm sensing this is quite restrictive when semantics and accessibility dictate that only a background image can be used. This would then beg the question... Did the webfont give us more flexibility all be it a slightly less robust / accessible solution? It seems the problem here is more around the use of background images.

**Comment by dominikwilkowski** [comment]
I'm just gona send you some links to answer this:

- https://twitter.com/derekjohnson/status/676838932907204609
- https://twitter.com/SaraSoueidan/status/676848127110987780
- https://twitter.com/zachleat/status/674277149155594240
- https://css-tricks.com/icon-fonts-vs-svg/

and an image:
![cvubncxuaaijmvv](https://cloud.githubusercontent.com/assets/1266923/11829983/0ea9d9ac-a3f5-11e5-843c-2be59a633d1f.png)

You may have misunderstood when we were talking about semantic icons. An icon font can never be accessible and you can embed as many icons as you want. My point was that we never show what the native color is that will show in older browsers.

**Comment by dominikwilkowski** [comment]
fixed via WestpacCXTeam/GUI-source#198
