### ISSUE TITLE
Investigate options for making the new breakpoint functionality more useful

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-docs#98]
EG
Move the grid indicator into each example iframe, so that it is clear how the elements work within their respective grids. This also allows the default view to be identified. - Indicating the grid structure of the entire page is not as important as showing how each element behaves.

Re-size/organise the page to allow the iframe to be wider to accommodate the different break points (currently anything larger then XS is cut off) we have loads of space on the page, is there a way to utilise it better?

Could the container be `max-width: 1800px;?

**Comment by justinspencer** [comment]
Agreed. We need to discuss this but I don't agree with this suggestion. This is exactly how the first GEL prototype was set up and it didn't work. We're going over the same ground.

There is a need to visualise how some elements respond at multiple breakpoints but there is no point in applying this to every element. I'd say about 15% of the elements in the GUI are actually responsive.

I thought we added the Layout section to do exactly this. Acting like a simulator we can set up a full page grid and place whatever elements we want into the grid to simulate how each element responds at the different breakpoints. This would also allow us to use nested grids which is another aspect of the grid system that we do not explain very well. Currently the Layout section offers no value.

Also, being able to show the outlining grid structure in the entire page has been one of the most useful aspects of the GUI. It is a simple, easy way to demonstrate how the grid works at a high level. It's also a great way to ensure that what we're building isn't broken.

**Comment by dominikwilkowski** [comment]
moved to WestpacCXTeam/GUI-source#226
